spring.application.name=Sprint Quiz 

spring.profiles.active=teste
#spring.profiles.default=teste
#desenvolvimento seria application.propert mesmo
#spring.profiles.active=desenvolvimento
#spring.profiles.active=producao
#
#definir profile ativo como argumento na vm
#caminho: botao direito no projeto > run as > run configurations... > arguments >
#-Dspring.profiles.active=desenvolvimento
#
#server.servlet.context-path=/api/v1
# server.port=8081

spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=Brazil/East
 
 role.padrao=ROLE_USER

#configs JWT
#duracao 30 min testar com 3600
security.jwt.expiracao=3600
#base64
security.jwt.chave-assinatura=bWV1IGdhdG8gc2UgY2hhbWEgbWFkcnVndWluaGE=


##configurando data-hora
spring.mvc.format.date=yyyy-MM-dd
spring.mvc.format.date-time=yyyy-MM-dd HH:mm:ss
spring.mvc.format.time=HH:mm:ss

#Configs swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.packagesToScan=com.etec.tcc.sprint_quiz.controller
springdoc.swagger-ui.use-root-path=true
