spring.application.name=Sprint Quiz 

#spring.profiles.active=desenvolvimento
#
#definir profile ativo como argumento na vm
#caminho: botao direito no projeto > run as > run configurations... > arguments >
#-Dspring.profiles.active=desenvolvimento
#
#server.servlet.context-path=/api/v1
# server.port=8081


#BANCO DE DADOS
spring.jpa.database=mysql
spring.datasource.url=jdbc:mysql://localhost/db_sprintquiz_tcc?createDatabaseIfNotExist=true&serverTimezone=America/Sao_Paulo&useSSl=false
spring.datasource.username=root
spring.datasource.password=159951

#configuring jpa properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.type=trace
#atualiza as modificacoes de tabela automaticamente
spring.jpa.defer-datasource-initialization=true
#spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect


spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=Brazil/East
 

#configs JWT
#duracao 30 min testar com 3600
security.jwt.expiracao=1000 * 60 * 30
#base64
security.jwt.chave-assinatura=bWV1IGdhdG8gc2UgY2hhbWEgbWFkcnVndWluaGE=


##configurando data-hora
spring.mvc.format.date=yyyy-MM-dd
spring.mvc.format.date-time=yyyy-MM-dd HH:mm:ss
spring.mvc.format.time=HH:mm:ss

#Configs swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.packagesToScan=com.etec.tcc.sprint_quiz.controller
springdoc.swagger-ui.use-root-path=true
