spring.application.name=Sprint Quiz 

#nao precisa habilitar
#spring.profiles.active=teste
#spring.profiles.default=teste

#server.servlet.context-path=/api/v1
 server.port=8081
 
 role.padrao=ROLE_USER


#Configs application datasource
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=

spring.datasource.driverClassName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#habilitando console visual e endereco de acesso
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#Habilitando visualizacao do codigo sql criado
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false


#configuring jpa properties
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.type=trace

#atualiza as modificacoes de tabela automaticamente
spring.jpa.defer-datasource-initialization=true
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create
spring.jpa.hibernate.ddl-auto=create-drop

#le o data.sql e inicializa as tabelas
spring.jpa.defer-datasource-initialization=true

# desabilita nome aleatorio para banco h2
spring.datasource.generate-unique-name=false
#verificar o que faz
spring.devtools.restart.enabled=false


#Configs Jackson
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=Brazil/East
 

#configs JWT
#duracao 30 min testar com 3600
security.jwt.expiracao=3600
#base64
security.jwt.chave-assinatura=bWV1IGdhdG8gc2UgY2hhbWEgbWFkcnVndWluaGE=

# desabilita nome aleatorio para banco h2
spring.datasource.generate-unique-name=false
#nao lembro o que faz
spring.devtools.restart.enabled=false


#configurando data-hora
spring.mvc.format.date=yyyy-MM-dd
spring.mvc.format.date-time=yyyy-MM-dd HH:mm:ss
spring.mvc.format.time=HH:mm:ss

#Configs swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.packagesToScan=com.etec.tcc.sprint_quiz.controller
springdoc.swagger-ui.use-root-path=true


